server:
  port: 8101

spring:
  application:
    name: chens-gateway
  devtools:
    restart:
      enabled: false #是否开启开发者工具
eureka:
  client:
    register-with-eureka: true #不注册到注册中心，web模块只用于消费服务
    fetchRegistry: true
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    serviceUrl:
      defaultZone: ${chens_eureka_serviceUrl:http://127.0.0.1:8761/eureka/} #注册中心地址
  instance:
    # 心跳间隔
        leaseRenewalIntervalInSeconds: 10
        hostname: ${HOSTNAME:localhost}

####################这里开始进入ZUUL配置###################################
zuul:
  # 代理普通http请求的超时时间
  host:
    socket-timeout-millis: 50000
    connect-timeout-millis: 50000
    # http连接池大小
    maxTotalConnections: 200
    # 每个host最大连接数
    maxPerRouteConnections: 20
  # 开启重试
  retryable: true
  # 路径前面加一个前缀(目前不加)
  #prefix: /api
  # 不代理某些服务，有些服务不对外公布，就可以在这里忽略掉
  # 比如sms-interface，我们不对外开放，可以在这里忽略掉，不然zuul从eureka获取到后就可以进行代理,如果是"*"表示全部忽略
  ignored-services:
  # hystrix 隔离策略，默认信号量(因为zuul中大量用到线程变量)。优先级要高过在hystrix中配置；
  ribbonIsolationStrategy: SEMAPHORE
  semaphore:
    # 信号量模式下，最大并发量。优先级要高过在hystrix中配置；
    maxSemaphores: 100

  # 路由配置
  # 通过配置文件配置的静态路由
  routes:
    # 指定了一个路由，Id为auth，在做验权的时候需要用到（这地方配的会被放行，详见自定义配置和TokenValidateFilter.shouldFilter）
    auth:
      # 登录。
      path: /authController/login
      # 这里表示，这个路由的实例信息，是通过ribbon负载均衡器进行获取的。值就是对应服务名
      serviceId: chens-admin-web
    logout:
      # 退出。
      path: /authController/logout
      # 这里表示，这个路由的实例信息，是通过ribbon负载均衡器进行获取的。值就是对应服务名
      serviceId: chens-admin-web
    register:
      # 注册。
      path: /authController/register
      # 这里表示，这个路由的实例信息，是通过ribbon负载均衡器进行获取的。值就是对应服务名
      serviceId: chens-admin-web
    parseToken:
      # 解析token。
      path: /authController/register
      # 这里表示，这个路由的实例信息，是通过ribbon负载均衡器进行获取的。值就是对应服务名
      serviceId: chens-admin-web
    share:
      path: /shareController/share
      serviceId: exam-wms

####################结束路由配置###################################

####################这里开始是filter相关配置###################################
# 禁用springcloud自带的errorfilter
SendErrorFilter:
  error:
    disable: true
# 开启自定义的token校验filter
TokenValidateFilter:
  pre:
    disable: false
####################filter配置结束###################################


ribbon:
  # 配置ribbon默认的超时时间
  ConnectTimeout: 50000
  ReadTimeout: 50000
  # 是否开启重试
  OkToRetryOnAllOperations: true
  # 重试期间，实例切换次数
  MaxAutoRetriesNextServer: 3
  # 当前实例重试次数
  MaxAutoRetries: 0

########hystrix相关配置
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    # 这是默认的配置
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            # 命令执行超时时间 20秒
            timeoutInMilliseconds: 20000

#########自定义配置
chens:
  zuul:
    tokenFilter:
      noAuthenticationRoutes:
        - auth
        - register
        - parseToken
        - share