server:
  port: 9001
  session:
    timeout: 600

eureka:
  client:
    #registerWithEureka: true #不注册到注册中心，web模块只用于消费服务
    #fetchRegistry: true
    # 服务列表缓存更新时间
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/ #注册中心地址

spring:
  application:
    name: chens-uua-server

# jwt相关的配置
token:
  jwt:
    key: a123456789
    # 发放者
    iss: chens-uaa-server
    # 有效期120分钟
    expm: 120
feign:
  hystrix:
    enabled: true;

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000